# This file is synced with beam-community/common-config. Any changes will be overwritten.

name: CI

on:
  merge_group:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  workflow_call:
    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
  workflow_dispatch:

concurrency:
  group: CI $\{{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Credo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: $\{{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Credo
        run: mix credo --strict

  Dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: $\{{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Unused
        run: mix deps.unlock --check-unused

  Dialyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: $\{{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Dialyzer
        run: mix dialyzer --format github

  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          github-token: $\{{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Format
        run: mix format --check-formatted

  Test:
{{#if IS_MIX_PACKAGE}}
    name: Test (Elixir $\{{ matrix.versions.elixir }} OTP $\{{ matrix.versions.otp }})

{{/if}}
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

{{#or POSTGRES_VERSION VALKEY_VERSION}}
    services:
  {{#if POSTGRES_VERSION}}
      postgres:
        image: postgres:{{ POSTGRES_VERSION }}-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_INITDB_ARGS: "--nosync"

  {{/if}}
  {{#if VALKEY_VERSION}}
      valkey:
        image: valkey/valkey:{{ VALKEY_VERSION }}
        ports:
          - 6379:6379
        volumes:
          - valkey_data:/data
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  {{/if}}
{{/or}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:{{#if IS_MIX_PACKAGE}}
          elixir-version: $\{{ matrix.versions.elixir }}{{/if}}
          github-token: $\{{ secrets.GH_PERSONAL_ACCESS_TOKEN }}{{#if IS_MIX_PACKAGE}}
          otp-version: $\{{ matrix.versions.otp }}{{/if}}

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Test
        run: mix test

{{#if IS_MIX_PACKAGE}}
    strategy:
      fail-fast: false
      matrix:
        versions:
          - elixir: 1.17
            otp: 27
          - elixir: 1.18
            otp: 27
          - elixir: 1.19
            otp: 27

{{/if}}